server:
  port: 8086

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smedia
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect

  liquibase:
    enabled: true
    drop-first: false
    default-schema: social_service
    change-log: classpath:db/changelog/changelog-master.xml

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER