swagger-api:
  version: "1.0"

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_DATABASE:skillbox}
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME:skillbox}
    password: ${DB_PASSWORD:skillbox}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        default_schema: skillbox

  liquibase:
    enabled: true
    drop-first: ${IS_DROP_FIRST:false}
    default-schema: skillbox
    change-log: classpath:db/changelog/changelog-master.xml

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  token:
    secret: skillboxJWTSecretsecretskillboxJWTSecretsecret

cloudinary:
    development:
      cloud_name: duvaewonz
      api_key: '354439898853154'
      api_secret: N-qIciSHT6v4toj9fvkqArfVzDw

white-list:
  links:
    - /**/login
    - /**/captcha
    - /**/register
    - /**/registration
    - /**/swagger-ui/*
#    - /api/v1/profile
#    - /api/v1/friends
#    - /api/v1/dialogs
#    - /api/v1/auth
#    - /api/v1/auth/captcha
#    - /api/v1/account
#    - /api/v1/post