spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smedia
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres

  liquibase:
    enabled: true
    drop-first: false
    default-schema: social_service
    change-log: classpath:db/changelog/changelog-master.xml

  jpa:
    show-sql: true