spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/skillbox
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  liquibase:
    enabled: true
    drop-first: false
    default-schema: skillbox
    change-log: classpath:db/changelog/changelog-master.xml

  jpa:
    show-sql: true